name: Github Action Demo
on: push
jobs:
  Premier-Job:
    name : Premier-Job
    runs-on : Ubuntu-latest
    steps:
      - run: echo "Premier Job"
      - run: echo "Fin 1 "
  Deuxieme-Job:
    needs: Premier-Job
    name : Deuxieme-Job
    runs-on : Ubuntu-latest
    steps:
      - run: echo "Deuxieme Job"
      - run: echo "Fin 2 "
